[INFO 15:25:09] pymarl Running command 'my_main'
[INFO 15:25:09] pymarl Started run with ID "2"
[DEBUG 15:25:09] pymarl Starting Heartbeat
[DEBUG 15:25:09] my_main Started
[INFO 15:25:09] my_main Experiment Parameters:
[INFO 15:25:09] my_main 

{   'agent': 'rnn',
    'batch_size': 1024,
    'batch_size_run': 32,
    'buffer_cpu_only': True,
    'buffer_size': 32,
    'checkpoint_path': '',
    'critic_lr': 0.0005,
    'cur_episodes': 32,
    'env': 'lbf',
    'env_args': {   'field_size': 20,
                    'force_coop': True,
                    'is_print': False,
                    'max_food': 4,
                    'need_render': False,
                    'partiteammate_observe': False,
                    'players': 2,
                    'remote': False,
                    'render_output_path': 'logs',
                    'seed': 1024,
                    'sight': 2},
    'episodes_per_teammate': 64,
    'epsilon_anneal_time': 1000000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'exp_name': 'stage1_LBF',
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'ind': 'stage1',
    'inner_loop_episodes': 128,
    'label': 'default_label',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'local_saves_path': 'saves',
    'log_interval': 10000,
    'lr': 0.0005,
    'mac': 'basic',
    'meta_update_times': 8,
    'n_sub_modules': 4,
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'optimize_meta': False,
    'points_per_teammate': 64,
    'pop': 'stage1',
    'population_alg': 'vdn',
    'population_size': 4,
    'repeat_id': 1,
    'rnn_hidden_dim': 64,
    'runner': 'meta',
    'runner_log_interval': 10000,
    'save_BR': False,
    'save_BR_episodes': 2048,
    'save_model': False,
    'save_model_interval': 2000000,
    'save_population': True,
    'save_population_episodes': 4096,
    'save_replay': False,
    'seed': 137776538,
    't_max': 5000000,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'test_percent': 0.2,
    'train_test_split': False,
    'use_cuda': True,
    'use_history': False,
    'use_tensorboard': True,
    'z_dim': 8}

[INFO 15:25:14] my_main ================ MetaEpoch: 0 ================
[INFO 15:25:14] my_main Time passed: 0 seconds
[INFO 15:25:14] root [Individual 0] Begin training for 128 episodes
Process Process-1:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Process Process-3:
Process Process-14:
Process Process-16:
Process Process-11:
Process Process-25:
Process Process-7:
Process Process-27:
Process Process-2:
Process Process-13:
Process Process-20:
Process Process-24:
Process Process-4:
Process Process-15:
Process Process-8:
Process Process-6:
Process Process-18:
Process Process-5:
Process Process-19:
Process Process-17:
Process Process-9:
Process Process-21:
Process Process-10:
Traceback (most recent call last):
Process Process-12:
Process Process-22:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
Process Process-23:
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Process Process-26:
Process Process-28:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
Traceback (most recent call last):
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
Traceback (most recent call last):
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
Traceback (most recent call last):
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
Traceback (most recent call last):
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Traceback (most recent call last):
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
Traceback (most recent call last):
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
Traceback (most recent call last):
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Process Process-29:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Process Process-32:
Process Process-31:
Process Process-30:
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cike/marl_collector/src/runners/meta_runner.py", line 40, in env_worker
    env.reset(data)
  File "/home/cike/marl_collector/src/envs/lbf/foraging.py", line 163, in reset
    self.obs = self.env.reset()
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 204, in env_reset_passive_checker
    check_obs(obs, env.observation_space, "reset")
  File "/home/cike/anaconda3/envs/pymarl/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 152, in check_obs
    ), f"{pre} length is not same as the observation space length, obs length: {len(obs)}, space length: {len(observation_space.spaces)}"
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
AssertionError: The obs returned by the `reset()` method length is not same as the observation space length, obs length: 21, space length: 2
